version: '3.8'

services:
 kucoin-feed:
  build:
   context: .
  ports:
  - 3080:3080
  volumes:
  - ./:/app
  # environment:
  # - PATH=/app/bin:$PATH
  # - PYTHONPATH=/app
  # command: "python main.py"

#  mysqldb:
#   image: mysql
#   ports:
#   - 3306:3306
#   environment:
#   - MYSQL_ROOT_PASSWORD=p@ssw0rd1
#   volumes:
#   - mysql:/var/lib/mysql
#   - mysql_config:/etc/mysql

# volumes:
#   mysql:
#   mysql_config: