version: '3.8'

services:
 realtimecryptobot:
  build:
   context: .
   # These argument variables are for build time only (this is just for my future reference as a programmer)
  #  args:
  #     KUCOIN_YOUR_API_KEY: ${KUCOIN_YOUR_API_KEY}
  #     KUCOIN_YOUR_SECRET: ${KUCOIN_YOUR_SECRET}
  #     KUCOIN_YOUR_PASS: ${KUCOIN_YOUR_PASS}
  environment:
    KUCOIN_YOUR_API_KEY: ${KUCOIN_YOUR_API_KEY}
    KUCOIN_YOUR_SECRET: ${KUCOIN_YOUR_SECRET}
    KUCOIN_YOUR_PASS: ${KUCOIN_YOUR_PASS}
    CBPRO_YOUR_API_KEY: ${CBPRO_YOUR_API_KEY}
    CBPRO_YOUR_SECRET: ${CBPRO_YOUR_SECRET}
    CBPRO_YOUR_PASS: ${CBPRO_YOUR_PASS}
    GEMINI_YOUR_API_KEY: ${GEMINI_YOUR_API_KEY}
    GEMINI_YOUR_SECRET: ${GEMINI_YOUR_SECRET}
  ports:
  - 3080:3080
  volumes:
  - ./:/app
  - ./db/:/app/db
  # This is the standard execution of the container.
  command: "python main.py"
  # If you want the container to be open after build for CLI commands.
  # command: tail -f /dev/null
  # If you must use pipenv comment out requirements.txt install and uncomment the pipenv run commands in dockerfile
  # command: "pipenv run python main.py"